### PR TITLE
docs!: Replace LICENSE with AGPL-3.0

### PR DESCRIPTION
**Pull request by LeoColman**
To match main repository's license, this commit replaces the current MIT
 license with the AGPL-3.0 license, used by the core repository
 https://github.com/open-meteo/open-meteo/blob/main/LICENSE

### CODE REVIEW

**Comment by DadiBit** [comment]
Hi, as decided back in [#79 on the main repo](https://github.com/open-meteo/open-meteo/issues/76#issuecomment-1204009699) I won't merge this pull request:

> For the license I would prefer MIT. While Open-Meteo is using AGPL-3.0 for the server, client libraries should be MIT.

As future reference, you can check the [open-meteo/sdk](https://github.com/open-meteo/sdk) repo, which actually has a Java sdk: since Java can be imported in Kotlin fairly easily, a Kotlin sdk might never get implemented, to be fair.

By the way, thank you for all the effort you're putting in all the PRs: it won't be wasted :smile:

**Comment by LeoColman** [comment]
For some reason I really liked how Open Meteo clicked with my Home Assistant setup and hyperfocused on taking a look at the Kotlin-SDK and making some commits as a "Hello, I'm here!" :D

> since Java can be imported in Kotlin fairly easily, a Kotlin sdk might never get implemented, to be fair.

I agree that it's easy to port Java into Kotlin-JVM. 
It's not possible to do the same in Kotlin-Multiplatform. 

Having a solid Kotlin SDK that looks and behaves like Kotlin is much better than just dropping the Java SDK in the project, my opinion as a heavy kotlin user. 
If you - from a open-meteo enthusiast perspective - think it's valid to have a complete SDK, I'd be more than happy to help you get to a very stable 1.0.0 release as evidenced by my initial hyperfocus 😅

**Comment by DadiBit** [comment]
> For some reason I really liked how Open Meteo clicked with my Home Assistant setup and hyperfocused on taking a look at the Kotlin-SDK and making some commits as a "Hello, I'm here!" :D

No worries! I appreciate someone is liking and wanting to work on the open-meteo project!


> I agree that it's easy to port Java into Kotlin-JVM. It's not possible to do the same in Kotlin-Multiplatform.
>
> Having a solid Kotlin SDK that looks and behaves like Kotlin is much better than just dropping the Java SDK in the project, my opinion as a heavy kotlin user. If you - from a open-meteo enthusiast perspective - think it's valid to have a complete SDK, I'd be more than happy to help you get to a very stable 1.0.0 release as evidenced by my initial hyperfocus 😅

The flatbuffer compiler didn't work properly with kmp back when I was talking with Patrick, so I just put everything to a halt, waiting for flatbuffers to be usable in kmp. My idea is to implement just the flatbuffers and ditch the json/protobufs serialization libraries.
In the upcoming hours, I'm checking what can be done with flatbuffers on kmp and push any updates.

To be honest, I had this idea of keeping alive this repo just a bit more and then letting it fade out in favour of a fresh one built for kmp in the sdk repo; if you have time and energy on working on "this" sdk, you're more then welcome to work on stabilizing it, or just add features :+1:

PS: The cool thing about flatbuffers is that you write the response schema just once, which is fantastic imo.

**Comment by LeoColman** [comment]
Is there any other project that is Open-Meteo Kotlin-SDK?
If not, I think we have a very solid scaffold here to build upon

**Comment by DadiBit** [comment]
> Is there any other project that is Open-Meteo Kotlin-SDK? If not, I think we have a very solid scaffold here to build upon

Right now there's only this one written in kotlin, but since the implementation of flatbuffers there were pretty much no updates to it. The java one has less "friendly" public elements for devs, imo, but should have full flatbuffer support out of the box.

Edit: I opened #12 to keep track of the flatbuffer and kmp implementation :)

**Pull request closed without merging**
